# Generated by Django 3.0.6 on 2020-05-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dick_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
